parameters:
- name: verbosity
  displayName: 'verbosity of this run'
  type: string
  default: Minimal
  values:
  - Detailed
  - Quiet
  - Diagnostic
  - Minimal

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src

pool:
  vmImage: ubuntu-latest

variables:
  dotNetVersion: '8.x'
  buildConfiguration: 'Release'
  testProjects: 'src/Tests/Pri.ConsoleApplicationBuilder.Tests.csproj'
  majorVersion: '0'
  minorVersion: '1'
  shortVersion: '$(majorVersion).$(minorVersion)'
  patchVersion: $[counter(variables['shortVersion'], 1)]
  versionPrefix: '$(majorVersion).$(minorVersion).$(patchVersion)'
  versionSuffixType: 'rc.'
  buildVersionKey: '$(majorVersion).$(minorVersion).$(patchVersion)$(versionSuffixType)'
  buildVersion: $[counter(variables['buildVersionKey'], 1)]
  versionSuffix: '$(versionSuffixType)$(buildVersion)'
  ${{ if eq(parameters.verbosity, 'Quiet') }}:
    dotnetVerbosity: q # Quiet
  ${{ elseif eq(parameters.verbosity, 'Detailed') }}:
    dotnetVerbosity: d # Detailed
  ${{ elseif eq(parameters.verbosity, 'Diagnostic') }}:
    dotnetVerbosity: diag # Diagnostic
  ${{ else }}:
    dotnetVerbosity: m # Minimal

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET SDK $(dotNetVersion)'
    inputs:
      packageType: sdk
      version: $(dotNetVersion)

  - task: DotNetCoreCLI@2
    displayName: 'Restore project dependencies'
    inputs:
      command: 'restore'
      projects: 'src/**/*.csproj'
      verbosityRestore: '${{ parameters.verbosity }}'

  - task: DotNetCoreCLI@2
    # run tests and publish results/coverage to Azure DevOps
    displayName: 'Dotnet Test - $(buildConfiguration)'
    inputs:
      command: 'test'
      projects: $(testProjects)
      arguments: >-
          -c $(buildConfiguration)
          --nologo
          -v $(dotnetVerbosity)
          /p:VersionSuffx=$(versionSuffix)
          /p:VersionPrefix=$(versionPrefix)
          /clp:ErrorsOnly
          --collect "Code coverage"
      testRunTitle: 'Dotnet Test - $(buildConfiguration)'

  - task: CopyFiles@2
    displayName: 'Copy package to artifact staging directory'
    inputs:
      SourceFolder: 'src'
      Contents: '**/*.nupkg'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      publishLocation: 'pipeline'

  - task: NuGetCommand@2
    displayName: 'NuGet Push'
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: 'TestNuGet - PRI-ConsoleApplicationBuilder'